### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by paf31**
- Request update to ensure container is on screen before calling `init`
- Update example to include a "smooth" toggle button

### CODE REVIEW

**Comment by paf31** [comment]
@cryogenian @jdegoes Could you please review? Thanks.

**Comment by jdegoes** [comment]
Is there any way we can push the version number into the library so we don't have to repeat the same logic for every chart?

**Comment by cryogenian** [comment]
Can we put `createContainer` logic to library too?

**Comment by paf31** [comment]
@jdegoes Yes, but it would involve wrapping the widget with `SF`. Not a bad thing, but I chose this way because it makes it clear when the widget gets repainted: when the version number changes. Hiding the version inside `SF` means you need to be aware of how the `EChartEvent` gets routed, and using things like `combine` make that less clear.

@cryogenian If we think that we're always going to create the container in the same way (`div` + width and height) then sure. It will be easy to partially apply this and provide a wrapper method.

**Pull request closed without merging**
