### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by paf31**
@jdegoes @cryogenian Could you please review this?

Obviously, this is subject to change if we change the way widgets are handled in Halogen, but I'd like to make sure this is a suitable way to use `Option` and `EChart`.

### CODE REVIEW

**Comment by paf31** [comment]
I'll update this for the new widget changes.

**Comment by jdegoes** [comment]
@cryogenian Can you please review, you're obviously very familiar with the echarts code? :laughing:

**Comment by cryogenian** [comment]
Code looks great, but I'm not sure that this will work because **echarts** requires elements with inner width and height. Going to check it in couple of hours.

**Comment by paf31** [comment]
@jdegoes @cryogenian This is updated for Halogen's changes, and I've added an example. 

The example doesn't work yet however, and I think @cryogenian is right about the width and height issue. This is a general issue with the way in which the components in widgets are created, I think, so we should probably decide on a fix.

The issue is that we need the `div` to have a width and height before we call `init`, but we I'm not sure if we can use an initializer hook because the context and node need to be returned immediately.

**Comment by paf31** [comment]
@jdegoes I accidentally "merged" this by using `git push origin master` instead of pushing to my personal repo, and now I can't revert from this page. I didn't realize I had push permissions, sorry about that.

Anyway, the code in `master` now works, including the example, but it's not ready to be released or used yet. 

I made it work by adding a `div` element to the document body, and then passing that node to `echarts`. This obviously won't work in a dynamic setting, so we probably will want to find a better solution.

Any ideas very welcome. I've tried setting things like `style.width` and `clientWidth` in code so far, with no luck.

**Comment by cryogenian** [comment]
Maybe we can check that node has been rendered and then init echarts on it in `update`?

**Comment by jdegoes** [comment]
@paf31 The node has to already be attached for echarts (and other libs) to work. It would be nice if Halogen's vdom `init` just added a container node, and then called a user-land `init` in the `update` function, at which point the container node would be a part of the DOM. Or something like that.

**Comment by paf31** [comment]
The issue is that `init` has to return both the node and the "context". 

I think what we need to do is modify `widget` in Halogen so that `update` can return a new context. Then, the context would start out as `Nothing` in `init`, and become `Just echart` after the first `update`. We also need to have `init` fire an event to rerender everything once the `div` is on screen, passing the initial `Option` record. 

The downside would be that we would render everything twice (ideally the diff would return no changes other than reattaching event handlers, of course).

**Comment by jdegoes** [comment]
Sounds like a workable patch, although long-term rendering things twice is not going to be desirable, especially for complex visualizations which take tens to hundreds of milliseconds to render.

**Comment by paf31** [comment]
Well the chart would only render once, I imagine, on the first `update`. With the new `widget`, it should now be easier to control when a chart gets rerendered, perhaps using the `version` trick or something else.

**Pull request merged**
