### PR TITLE
0.9-updates

### PR DESCRIPTION
**Pull request by cryogenian**

### CODE REVIEW

**Comment by garyb** [comment]
I'm holding off on the `-halogen` updates as there's another breaking change coming: slamdata/purescript-halogen#317

**Comment by cryogenian** [comment]
Ok, should I close this or just leave it here?

**Comment by garyb** [comment]
May as well keep this open and just update it once the new Halogen release goes out :) I don't think it will break anything here.

**Comment by garyb** [comment]
That Halogen PR has been merged now, so if you bump the dependency to `^0.10.0` this is good to go :+1:

**Comment by cryogenian** [comment]
bumped

**Comment by garyb** [comment]
Looks like some other dependency requires a different version of Halogen? The travis error is a problem with resolving a suitable version, not that 0.10 doesn't exist, I think. (It definitely does).

**Comment by cryogenian** [comment]
Sorry, hopefully should work now

**Comment by garyb** [comment]
:tada:

**Pull request merged**
