### PR TITLE
Performance improvement - call resize only when necessary.

### PR DESCRIPTION
**Pull request by krisajenkins**
A user of this library specifies the dimensions of the chart in their
render call. That means that every time their render function is
called, `eval SetDimensions ...` is invoked, which in turn calls echarts'
`resize` function, which is a _relatively_ expensive call.

This change ensures that resize is only triggered if the dimensions of
the chart have actually changed.

### CODE REVIEW

**Comment by cryogenian** [comment]
Initial approach was to handle dimensions of this component in its parent --> that's why input type is `{width: Maybe Int, height: Maybe Int}`. I agree that this is more convenient, but in this case we don't need `Maybe` wrappers anymore, could you please remove them?

**Comment by cryogenian** [comment]
Thanks a lot! Could you please sign CLA? :)

**Comment by garyb** [comment]
Maybe it's due to this?

> Kris Jenkins seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.
You have signed the CLA already but the status is still pending? Let us recheck it.

Suggests the git client is configured with a different email than used in GH I think.

**Comment by garyb** [comment]
Looks like it did the trick! :)

**Pull request merged**
