### PR TITLE
update purescript-echarts

### PR DESCRIPTION
**Pull request by shujuwen2013**
update purescript-echarts

### CODE REVIEW

**Comment by garyb** [comment]
I'm sure this is fine but I'll wait for Travis to pass and then merge it... not sure what's taking so long for it to actually start the build!

**Comment by shujuwen2013** [comment]
Yes, it's weird. Is there anything I can do?

**Comment by garyb** [comment]
I don't think so, it seems to be an issue with Travis. I tried cancelling the job and restarting it, but no luck.

I'll merge it now anyway, I checked it out locally and the build succeeded, so :+1:

**Comment by shujuwen2013** [comment]
Thanks

**Pull request merged**
